### ISSUE TITLE
Relationships return not JSON API spec complaint 

### ISSUE THREAD

**Issue by scryba** [nilportugues/laravel5-jsonapi#72] opened 2016-06-18 11:10 UTC
JSON API response for /accounts/11e61481e3b68640b31b63eae8eae225

```js
{  
   "data":{  
      "type":"accounts",
      "id":"11e61481e3b68640b31b63eae8eae225",
      "relationships":{  
         "country":[  
            {  
               "data":{  
                  "type":"country",
                  "id":"418977"
               }
            }
         ]
      }
   }
}
```

this is not working well with ember.js when getting relationships.

but rather the correct response should be: 

```js
{
  "data": {
    "type": "accounts",
    "id": "11e61481e3b68640b31b63eae8eae225",
    "relationships": {
      "country": {
        "data": {
          "id": "418977",
          "type": "country"
        }
      }
    }
  }
}
```

or 

```js
{  
   "data":{  
      "type":"accounts",
      "id":"11e61481e3b68640b31b63eae8eae225",
      "relationships":{  
         "country":{  
            "data":[  
               {  
                  "id":"418977",
                  "type":"country"
               },
               {  
                  "id":"413111",
                  "type":"country"
               }
            ]
         }
      }
   }
}
```

**Comment by scryba** [comment] 2016-06-18 17:49
Amazingly now relationships are no longer included in the response.
what are my doing wrong?.

`{
  "data": {
    "type": "accounts",
    "id": "11e5fef7a59de46087ae2d0c4686f693",
    "attributes": {
      "title": "yo",
      "firstname": "yokhh",
      "lastname": "jhjh",
      "othernames": "sometimes",
      "email": "ladd@dkd.cc",
      "phone": "8888888888",
      "sender-id": "",
      "num-sender-id": "",
      "account-balance": "0.0000",
      "ref-code": "",
      "phone-validated": 0,
      "email-validated": 0,
      "created-at": "2016-04-10 08:38:49",
      "updated-at": "2016-04-10 08:49:52"
    },
    "links": {
      "self": {
        "href": "/accounts/11e5fef7a59de46087ae2d0c4686f693"
      }
    }
  },
  "jsonapi": {
    "version": "1.0"
  }
}`

for /accounts/
`{
  "data": [
    {
      "type": "accounts",
      "id": "11e5fef782606a20b1e00b17cd71eddb",
      "attributes": {
        "title": "Dr.",
        "firstname": "Adah",
        "lastname": "Jast",
        "othernames": "PhD",
        "email": "giles49@strch.or",
        "phone": "24799611375",
        "sender-id": "colten.bauc",
        "num-sender-id": "4424799611375",
        "account-balance": "415.0000",
        "ref-code": "61928284",
        "phone-validated": 1,
        "email-validated": 1,
        "created-at": "2016-04-10 08:37:50",
        "updated-at": "2016-04-10 08:37:50"
      },
      "links": {
        "self": {
          "href": "/accounts/11e5fef782606a20b1e00b17cd71eddb"
        }
      }
    },
    {
      "type": "accounts",
      "id": "11e5fef78277ec60a9ed7334df772b95",
      "attributes": {
        "title": "Miss",
        "firstname": "Antonette",
        "lastname": "Towne",
        "othernames": "DDS",
        "email": "cert@g.co",
        "phone": "84647122340",
        "sender-id": "vkassulke",
        "num-sender-id": "4784647122340",
        "account-balance": "329.0000",
        "ref-code": "81715031",
        "phone-validated": 1,
        "email-validated": 1,
        "created-at": "2016-04-10 08:37:50",
        "updated-at": "2016-04-10 08:37:50"
      },
      "links": {
        "self": {
          "href": "/accounts/11e5fef78277ec60a9ed7334df772b95"
        }
      }
    },
    {
      "type": "accounts",
      "id": "11e5fef7a59de46087ae2d0c4686f693",
      "attributes": {
        "title": "yo",
        "firstname": "yokhh",
        "lastname": "jhjh",
        "othernames": "sometimes",
        "email": "ladd@dkd.cc",
        "phone": "8888888888",
        "sender-id": "",
        "num-sender-id": "",
        "account-balance": "0.0000",
        "ref-code": "",
        "phone-validated": 0,
        "email-validated": 0,
        "created-at": "2016-04-10 08:38:49",
        "updated-at": "2016-04-10 08:49:52"
      },
      "links": {
        "self": {
          "href": "/accounts/11e5fef7a59de46087ae2d0c4686f693"
        }
      }
    },
    {
      "type": "accounts",
      "id": "11e607267bbc98608680e952055a440a",
      "attributes": {
        "title": "Mr.",
        "firstname": "John",
        "lastname": "Doe",
        "othernames": "No-Name",
        "email": "you@go.com",
        "phone": "+233267270910",
        "sender-id": "ScrybaTest",
        "num-sender-id": "233267270920",
        "account-balance": "0.0000",
        "ref-code": "ZJSgQ4K3Wl",
        "phone-validated": 0,
        "email-validated": 0,
        "created-at": "2016-04-20 18:34:14",
        "updated-at": "2016-04-20 18:34:14"
      },
      "links": {
        "self": {
          "href": "/accounts/11e607267bbc98608680e952055a440a"
        }
      }
    }
  ],
  "included": [],
  "links": {
    "self": {
      "href": "/accounts?page[number]=1&page[size]=10"
    },
    "first": {
      "href": "/accounts?page[number]=1&page[size]=10"
    },
    "last": {
      "href": "/accounts?page[number]=1&page[size]=10"
    }
  },
  "meta": {
    "page": {
      "total": 4,
      "last": 1,
      "number": 1,
      "size": 10
    }
  },
  "jsonapi": {
    "version": "1.0"
  }
}`

**Comment by nilportugues** [comment] 2016-06-22 14:06
@scryba

Done some investigations. I can confirm this is due to eloquent, not the underlying nilportugues/json-api package, but most likely the eloquent-driver.

At least I know where I can look for the error. Thanks. 

Keep you posted

**Comment by scryba** [comment] 2016-06-22 15:12
@nilportugues that's great, i am hopeful you will resolve the issue.

**Comment by nilportugues** [comment] 2016-06-22 15:13
@scryba about to release the fix.

**Comment by nilportugues** [comment] 2016-06-22 15:14
https://github.com/nilportugues/laravel5-jsonapi/releases/tag/2.3.0

**Comment by scryba** [comment] 2016-06-22 15:33
Nice running composer update now. will give feedback soon

**Comment by scryba** [comment] 2016-06-22 17:41
working perfectly with has many relationship

Has Many Relationship:

`"relationships":{  
   "users":{  
      "data":[  
         {  
            "type":"accounts",
            "id":"11e5fef782606a20b1e00b17cd71eddb"
         },
         {  
            "type":"accounts",
            "id":"11e5fef7a59de46087ae2d0c4686f693"
         }
      ]
   }
}`

Belongs to relationship is good now but with a little tweaking;
it returns data as an array with should not be the case;

`"relationships":{  
   "country":{  
      "data":[  
         {  
            "type":"country",
            "id":"416201"
         }
      ]
   }
}`

it should rather be

`"relationships":{  
   "country":{  
      "data":{  
         "type":"country",
         "id":"416201"
      }
   }
}`

**Comment by nilportugues** [comment] 2016-06-22 21:09
@scryba new fix. Composer update to fetch it :+1:

**Comment by scryba** [comment] 2016-06-23 07:48
@nilportugues I don't know if this is from my side after running composer update 
the belongs to relationship is still the same.

this is my user model;

```
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    protected $table = 'users';
    public $timestamps = true;

    use SoftDeletes;

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are not mass assignable. "black list"
     *
     * @var array
     */
    protected $guarded = [
        'id', 'remember_token', 'created_at', 'updated_at', 'deleted_at',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        "password",
        "remember_token",
        "deleted_at",
    ];


    // Relations
    public function country()
    {
        return $this->belongsTo(Country::class);
    }

}

```

my country model

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{

    /**
     * The attributes that are not mass assignable. "black list"
     *
     * @var array
     */
    protected $guarded = [
        'id',
    ];

    // Relations
   public function users()
    {
        return $this->hasMany(User::class)->limit(10);
    }
}

```

my transformers

```
<?php

namespace Transformers\V1;

use NilPortugues\Api\Mappings\JsonApiMapping;
use App\Models\Country;

class CountryTransformer implements JsonApiMapping
{
    /**
     * Returns a string with the full class name, including namespace.
     *
     * @return string
     */
    public function getClass()
    {
        return Country::class;
    }

    /**
     * Returns a string representing the resource name 
     * as it will be shown after the mapping.
     *
     * @return string
     */
    public function getAlias()
    {
        return 'country';
    }

    /**
     * Returns an array of properties that will be renamed.
     * Key is current property from the class. 
     * Value is the property's alias name.
     *
     * @return array
     */
    public function getAliasedProperties()
    {
        return [
            'long_name' => 'long-name',
            'numeric_code' => 'numeric-code',
            'created_at' => 'created-at',
            'updated_at' => 'updated-at',

        ];
    }

    /**
     * List of properties in the class that will be  ignored by the mapping.
     *
     * @return array
     */
    public function getHideProperties()
    {
        return [
            //'attachments'
        ];
    }

    /**
     * Returns an array of properties that are used as an ID value.
     *
     * @return array
     */
    public function getIdProperties()
    {
        return ['id'];
    }

    /**
     * Returns a list of URLs. This urls must have placeholders 
     * to be replaced with the getIdProperties() values.
     *
     * @return array
     */
    public function getUrls()
    {
        return [
            'self' => ['name' => '', 'as_id' => 'id'],
            //'self' => ['name' => 'countries.show', 'as_id' => 'id'],
            //'employees' => ['name' => 'employees.index'],
            //'employee_orders' => ['name' => 'employees.orders', 'as_id' => 'id']
        ];
    }

    /**
     * Returns an array containing the relationship mappings as an array.
     * Key for each relationship defined must match a property of the mapped class.
     *
     * @return array
     */
    public function getRelationships()
    {
        return [];
    }

}
```


```
<?php

namespace Transformers\V1;

use NilPortugues\Api\Mappings\JsonApiMapping;
use App\Models\User;

class UserTransformer implements JsonApiMapping
{
    /**
     * Returns a string with the full class name, including namespace.
     *
     * @return string
     */
    public function getClass()
    {
        return User::class;
    }

    /**
     * Returns a string representing the resource name
     * as it will be shown after the mapping.
     *
     * @return string
     */
    public function getAlias()
    {
        return 'accounts';
    }

    /**
     * Returns an array of properties that will be renamed.
     * Key is current property from the class.
     * Value is the property's alias name.
     *
     * @return array
     */
    public function getAliasedProperties()
    {
        return [
            "account_balance" => "account-balance",
            "email_validated" => 'email-validated',
            'created_at' => 'created-at',
            'updated_at' => 'updated-at',
        ];
    }

    /**
     * List of properties in the class that will be  ignored by the mapping.
     * Same as Model's  protected $hidden = [] attribute.
     * @return array
     */
    public function getHideProperties()
    {
        return [
            "password",
            "remember_token",
            "deleted_at",
        ];
    }

    /**
     * Returns an array of properties that are used as an ID value.
     *
     * @return array
     */
    public function getIdProperties()
    {
        return ['id'];
    }

    /**
     * Returns a list of URLs. This urls must have placeholders
     * to be replaced with the getIdProperties() values.
     *
     * @return array
     */
    public function getUrls()
    {
        return [
            'self' => ['name' => '', 'as_id' => 'id'],
            //'self' => ['name' => 'accounts.show', 'as_id' => 'id'],
            //'employees' => ['name' => 'employees.index'],
            //'employee_orders' => ['name' => 'employees.orders', 'as_id' => 'id']
        ];
    }

    /**
     * Returns an array containing the relationship mappings as an array.
     * Key for each relationship defined must match a property of the mapped class.
     *
     * @return array
     */
    public function getRelationships()
    {
        return [
            /*'country' => [ //this key must match with the property or alias of the same name in Post class.
                'related' => 'http://example.com/posts/{postId}/author',
                'self' => 'http://example.com/posts/{postId}/relationships/author',
            ]*/
        ];
    }

}

```

Then config/jsonapi.php

```
<?php
use App\Transformers\V1\UserTransformer;
use App\Transformers\V1\CountryTransformer;

return [
    UserTransformer::class,
    CountryTransformer::class,
];
```

**Comment by nilportugues** [comment] 2016-06-23 08:02
Your mappings look fine. 

This helps recreating the model on my side.

**Comment by directrix1** [comment] 2016-06-24 01:23
Neat, this is what I was looking into today. If it's a has many relationship (i.e. returns an Eloquent Collection) it must be encapsulated in the array form, from the spec:

> A logical collection of resources MUST be represented as an array, even if it only contains one item or is empty.

Whereas, if it's a single object then it's not encapsulated in the array.

**Comment by directrix1** [comment] 2016-06-24 22:05
I submitted a pull request with a fix for this to the eloquent driver's project.

**Comment by nilportugues** [comment] 2016-06-24 22:58
Already merged.

Composer update should bring the update to you all. Hopefully we can get this fixed thanks to your fix @directrix1. Thank you :+1:

**Comment by scryba** [comment] 2016-06-25 00:41
@nilportugues  and @directrix1 . works fine now, Great Work!!

**Comment by scryba** [comment] 2016-06-25 00:44
@nilportugues does it work well with https://github.com/dingo/api  

i get error when running composer update;
Error:

```
composer update
> php artisan clear-compiled


  [Exception]
  Provided route name does not exist


Script php artisan clear-compiled handling the pre-update-cmd event returned with an error


  [RuntimeException]
  Error Output:
```

**Comment by nilportugues** [comment] 2016-06-25 08:29
Dingo has its own routing system separate from laravel so it won't work due to this reason.

**Closed by nilportugues** 2016-06-25 08:29 UTC
Labels: bug
